apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-master
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: pfetotalenergies.azurecr.io/seifv/hello-node
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
          name: nodejs-port
